import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-red">
      <Head>
        <title>Create next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
        <form className="bg-white flex rounded-lg w-1/2 ">
          <div className="flex-1 text-gray-700 p-20    ">
            <h1 className="text-3xl pb-2">Let's get started !!</h1>
            <p className="text-lg text-gray-500">
              join our E-learning platform today unlock a crash course and
              digital assets
            </p>
            <div className="pd-4">
              {/* input field for name */}
              <div>
                <label className="pb-2 block text-sm" htmlFor="name">
                  Name
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  type="name"
                  name="name"
                  placeholder="Enter Your Name"
                />
              </div>
              {/* email field for email */}
              <div>
                <label className="pb-2 block text-sm" htmlFor="name">
                  Email
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  type="email"
                  name="email"
                  placeholder="Enter Your Email"
                />
              </div>
              {/* country checkbox for nation*/}
              <div>
                <label className="pb-2 block text-sm" htmlFor="name">
                  Country
                </label>
                <select
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 "
                  name="country"
                >
                  <option>India</option>
                  <option>USA</option>
                  <option>UK</option>
                  <option>AUS</option>
                </select>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
}
